config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'static_pages/home'
  get '/contact',   to: 'static_pages#contact'
  get '/about',     to: 'static_pages#about'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
  <footer class="footer">
      <small>
          Assignment2 by <a href="https://www.linkedin.com/in/faisal-maqsood-31a9b41a/">Faisal Maqsood</a>
          Student Number 2847484
      </small>
        <%= link_to "assignment1", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact",   contact_path %></li>
            <li><a href="https://www.linkedin.com/in/faisal-maqsood-31a9b41a/">Linkedin</a></li>
          </ul>
        </nav>
      </div>
    </footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Assignment2", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Contact",  contact_path %></li>
             <% if logged_in? %>
             <li><%= link_to "Users", users_path %></li>
             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
             
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_default.html.erb
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  </head>
<body>
  <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>